### ISSUE TITLE
Notifications doesn't sent in threads (slack uses float representation for thread timestamps)

### ISSUE THREAD

**Issue by lptn** [spatie/interactive-slack-notification-channel#2]
```php
public function threadTimestamp(DateTimeInterface|DateInterval|int $threadTimestamp): self
{
    $this->threadTimestamp = $threadTimestamp;

    return $this;
}
```

it doesn't work anymore, at lest with `int`. $response['ts'] looks like `1629118036.001600`

**Comment by freekmurze** [comment]
would it be fixed by also allowing a float?

If so, feel free to PR that.

**Comment by lptn** [comment]
thanks @freekmurze , I've just created 2 PRs
 - Use new format of thread timestamp #5
 - Add very-very basic docs #4

Sorry, didn't have enough time to write tests, but can say for sure that this fixed version works on my end

**Comment by freekmurze** [comment]
Fixed by your PR.
